# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wagner/Dropbox/Wagner/C++/TCC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wagner/Dropbox/Wagner/C++/TCC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wagner/Dropbox/Wagner/C++/TCC/CMakeFiles /home/wagner/Dropbox/Wagner/C++/TCC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wagner/Dropbox/Wagner/C++/TCC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TCC

# Build rule for target.
TCC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TCC
.PHONY : TCC

# fast build rule for target.
TCC/fast:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/build
.PHONY : TCC/fast

Config.o: Config.cpp.o

.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i

.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s

.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Config.cpp.s
.PHONY : Config.cpp.s

Coord.o: Coord.cpp.o

.PHONY : Coord.o

# target to build an object file
Coord.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Coord.cpp.o
.PHONY : Coord.cpp.o

Coord.i: Coord.cpp.i

.PHONY : Coord.i

# target to preprocess a source file
Coord.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Coord.cpp.i
.PHONY : Coord.cpp.i

Coord.s: Coord.cpp.s

.PHONY : Coord.s

# target to generate assembly for a file
Coord.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Coord.cpp.s
.PHONY : Coord.cpp.s

GeneticAI/CodeGenerator.o: GeneticAI/CodeGenerator.cpp.o

.PHONY : GeneticAI/CodeGenerator.o

# target to build an object file
GeneticAI/CodeGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/CodeGenerator.cpp.o
.PHONY : GeneticAI/CodeGenerator.cpp.o

GeneticAI/CodeGenerator.i: GeneticAI/CodeGenerator.cpp.i

.PHONY : GeneticAI/CodeGenerator.i

# target to preprocess a source file
GeneticAI/CodeGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/CodeGenerator.cpp.i
.PHONY : GeneticAI/CodeGenerator.cpp.i

GeneticAI/CodeGenerator.s: GeneticAI/CodeGenerator.cpp.s

.PHONY : GeneticAI/CodeGenerator.s

# target to generate assembly for a file
GeneticAI/CodeGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/CodeGenerator.cpp.s
.PHONY : GeneticAI/CodeGenerator.cpp.s

GeneticAI/Dna.o: GeneticAI/Dna.cpp.o

.PHONY : GeneticAI/Dna.o

# target to build an object file
GeneticAI/Dna.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Dna.cpp.o
.PHONY : GeneticAI/Dna.cpp.o

GeneticAI/Dna.i: GeneticAI/Dna.cpp.i

.PHONY : GeneticAI/Dna.i

# target to preprocess a source file
GeneticAI/Dna.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Dna.cpp.i
.PHONY : GeneticAI/Dna.cpp.i

GeneticAI/Dna.s: GeneticAI/Dna.cpp.s

.PHONY : GeneticAI/Dna.s

# target to generate assembly for a file
GeneticAI/Dna.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Dna.cpp.s
.PHONY : GeneticAI/Dna.cpp.s

GeneticAI/GeneChain.o: GeneticAI/GeneChain.cpp.o

.PHONY : GeneticAI/GeneChain.o

# target to build an object file
GeneticAI/GeneChain.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/GeneChain.cpp.o
.PHONY : GeneticAI/GeneChain.cpp.o

GeneticAI/GeneChain.i: GeneticAI/GeneChain.cpp.i

.PHONY : GeneticAI/GeneChain.i

# target to preprocess a source file
GeneticAI/GeneChain.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/GeneChain.cpp.i
.PHONY : GeneticAI/GeneChain.cpp.i

GeneticAI/GeneChain.s: GeneticAI/GeneChain.cpp.s

.PHONY : GeneticAI/GeneChain.s

# target to generate assembly for a file
GeneticAI/GeneChain.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/GeneChain.cpp.s
.PHONY : GeneticAI/GeneChain.cpp.s

GeneticAI/Organism.o: GeneticAI/Organism.cpp.o

.PHONY : GeneticAI/Organism.o

# target to build an object file
GeneticAI/Organism.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Organism.cpp.o
.PHONY : GeneticAI/Organism.cpp.o

GeneticAI/Organism.i: GeneticAI/Organism.cpp.i

.PHONY : GeneticAI/Organism.i

# target to preprocess a source file
GeneticAI/Organism.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Organism.cpp.i
.PHONY : GeneticAI/Organism.cpp.i

GeneticAI/Organism.s: GeneticAI/Organism.cpp.s

.PHONY : GeneticAI/Organism.s

# target to generate assembly for a file
GeneticAI/Organism.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Organism.cpp.s
.PHONY : GeneticAI/Organism.cpp.s

GeneticAI/Permutations.o: GeneticAI/Permutations.cpp.o

.PHONY : GeneticAI/Permutations.o

# target to build an object file
GeneticAI/Permutations.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Permutations.cpp.o
.PHONY : GeneticAI/Permutations.cpp.o

GeneticAI/Permutations.i: GeneticAI/Permutations.cpp.i

.PHONY : GeneticAI/Permutations.i

# target to preprocess a source file
GeneticAI/Permutations.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Permutations.cpp.i
.PHONY : GeneticAI/Permutations.cpp.i

GeneticAI/Permutations.s: GeneticAI/Permutations.cpp.s

.PHONY : GeneticAI/Permutations.s

# target to generate assembly for a file
GeneticAI/Permutations.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/GeneticAI/Permutations.cpp.s
.PHONY : GeneticAI/Permutations.cpp.s

IGMN/constants.o: IGMN/constants.cpp.o

.PHONY : IGMN/constants.o

# target to build an object file
IGMN/constants.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/constants.cpp.o
.PHONY : IGMN/constants.cpp.o

IGMN/constants.i: IGMN/constants.cpp.i

.PHONY : IGMN/constants.i

# target to preprocess a source file
IGMN/constants.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/constants.cpp.i
.PHONY : IGMN/constants.cpp.i

IGMN/constants.s: IGMN/constants.cpp.s

.PHONY : IGMN/constants.s

# target to generate assembly for a file
IGMN/constants.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/constants.cpp.s
.PHONY : IGMN/constants.cpp.s

IGMN/igmn.o: IGMN/igmn.cpp.o

.PHONY : IGMN/igmn.o

# target to build an object file
IGMN/igmn.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/igmn.cpp.o
.PHONY : IGMN/igmn.cpp.o

IGMN/igmn.i: IGMN/igmn.cpp.i

.PHONY : IGMN/igmn.i

# target to preprocess a source file
IGMN/igmn.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/igmn.cpp.i
.PHONY : IGMN/igmn.cpp.i

IGMN/igmn.s: IGMN/igmn.cpp.s

.PHONY : IGMN/igmn.s

# target to generate assembly for a file
IGMN/igmn.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/igmn.cpp.s
.PHONY : IGMN/igmn.cpp.s

IGMN/statistic.o: IGMN/statistic.cpp.o

.PHONY : IGMN/statistic.o

# target to build an object file
IGMN/statistic.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/statistic.cpp.o
.PHONY : IGMN/statistic.cpp.o

IGMN/statistic.i: IGMN/statistic.cpp.i

.PHONY : IGMN/statistic.i

# target to preprocess a source file
IGMN/statistic.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/statistic.cpp.i
.PHONY : IGMN/statistic.cpp.i

IGMN/statistic.s: IGMN/statistic.cpp.s

.PHONY : IGMN/statistic.s

# target to generate assembly for a file
IGMN/statistic.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/IGMN/statistic.cpp.s
.PHONY : IGMN/statistic.cpp.s

MockUps.o: MockUps.cpp.o

.PHONY : MockUps.o

# target to build an object file
MockUps.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/MockUps.cpp.o
.PHONY : MockUps.cpp.o

MockUps.i: MockUps.cpp.i

.PHONY : MockUps.i

# target to preprocess a source file
MockUps.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/MockUps.cpp.i
.PHONY : MockUps.cpp.i

MockUps.s: MockUps.cpp.s

.PHONY : MockUps.s

# target to generate assembly for a file
MockUps.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/MockUps.cpp.s
.PHONY : MockUps.cpp.s

PointsGenerator.o: PointsGenerator.cpp.o

.PHONY : PointsGenerator.o

# target to build an object file
PointsGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/PointsGenerator.cpp.o
.PHONY : PointsGenerator.cpp.o

PointsGenerator.i: PointsGenerator.cpp.i

.PHONY : PointsGenerator.i

# target to preprocess a source file
PointsGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/PointsGenerator.cpp.i
.PHONY : PointsGenerator.cpp.i

PointsGenerator.s: PointsGenerator.cpp.s

.PHONY : PointsGenerator.s

# target to generate assembly for a file
PointsGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/PointsGenerator.cpp.s
.PHONY : PointsGenerator.cpp.s

Simulator.o: Simulator.cpp.o

.PHONY : Simulator.o

# target to build an object file
Simulator.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Simulator.cpp.o
.PHONY : Simulator.cpp.o

Simulator.i: Simulator.cpp.i

.PHONY : Simulator.i

# target to preprocess a source file
Simulator.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Simulator.cpp.i
.PHONY : Simulator.cpp.i

Simulator.s: Simulator.cpp.s

.PHONY : Simulator.s

# target to generate assembly for a file
Simulator.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/Simulator.cpp.s
.PHONY : Simulator.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TCC.dir/build.make CMakeFiles/TCC.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... TCC"
	@echo "... edit_cache"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... Coord.o"
	@echo "... Coord.i"
	@echo "... Coord.s"
	@echo "... GeneticAI/CodeGenerator.o"
	@echo "... GeneticAI/CodeGenerator.i"
	@echo "... GeneticAI/CodeGenerator.s"
	@echo "... GeneticAI/Dna.o"
	@echo "... GeneticAI/Dna.i"
	@echo "... GeneticAI/Dna.s"
	@echo "... GeneticAI/GeneChain.o"
	@echo "... GeneticAI/GeneChain.i"
	@echo "... GeneticAI/GeneChain.s"
	@echo "... GeneticAI/Organism.o"
	@echo "... GeneticAI/Organism.i"
	@echo "... GeneticAI/Organism.s"
	@echo "... GeneticAI/Permutations.o"
	@echo "... GeneticAI/Permutations.i"
	@echo "... GeneticAI/Permutations.s"
	@echo "... IGMN/constants.o"
	@echo "... IGMN/constants.i"
	@echo "... IGMN/constants.s"
	@echo "... IGMN/igmn.o"
	@echo "... IGMN/igmn.i"
	@echo "... IGMN/igmn.s"
	@echo "... IGMN/statistic.o"
	@echo "... IGMN/statistic.i"
	@echo "... IGMN/statistic.s"
	@echo "... MockUps.o"
	@echo "... MockUps.i"
	@echo "... MockUps.s"
	@echo "... PointsGenerator.o"
	@echo "... PointsGenerator.i"
	@echo "... PointsGenerator.s"
	@echo "... Simulator.o"
	@echo "... Simulator.i"
	@echo "... Simulator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

